apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: dehydrated-namecheap
  name: dehydrated-namecheap-dhnv
  namespace: ingress-controller
data:
  # Dehydrated NameCheap hook configuration
  # Set variables as described in https://github.com/wdouglascampbell/dehydrated_namecheap_dns_api_hook/blob/master/config
  # DEBUG: "yes"
  RELOAD_SCRIPT: /app_files/reload_services.sh

  SENDER: "cert@example.cloud"
  RECIPIENT: sysadmin@example.cloud
  MAIL_METHOD: SMTP
  SMTP_SERVER: "localhost"
  SMTP_PORT: "25"
