apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: dehydrated-namecheap
  name: dehydrated-namecheap
  namespace: ingress-controller
data:
  domains.txt: |
    # https://github.com/lukas2511/dehydrated/blob/master/docs/examples/domains.txt
    example.cloud *.example.cloud
  reload_services.sh: |
    #!/usr/bin/env bash
    set -x
    DOMAIN="${1}" KEYFILE="${2}" CERTFILE="${3}" FULLCHAINFILE="${4}" CHAINFILE="${5}" TIMESTAMP="${6}"

    kubectl create secret tls dehydrated-namecheap-cert --key $KEYFILE --cert $FULLCHAINFILE --dry-run -o yaml | kubectl apply -f -

    for pod in $(kubectl get pod -n ingress-controller -l run=haproxy-ingress -o jsonpath='{.items[*].metadata.name}'); do
      kubectl -n ingress-controller exec $pod -- /haproxy-reload.sh native /etc/haproxy/haproxy.cfg
    done
