apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: dehydrated-namecheap
  name: dehydrated-namecheap-dhv
  namespace: ingress-controller
data:
  # Dehydrated configuration
  # Set variables as described in https://github.com/lukas2511/dehydrated/blob/master/docs/examples/config
  # CA: https://acme-v02.api.letsencrypt.org/directory
  CA: https://acme-staging-v02.api.letsencrypt.org/directory
  CONTACT_EMAIL: sysadmin@example.cloud
  IP_VERSION: "4"
  CHALLENGETYPE: dns-01
  DOMAINS_TXT: /app_files/domains.txt
