apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: dehydrated-namecheap
  name: dehydrated-namecheap
  namespace: ingress-controller
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi