apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: dehydrated-namecheap
  name: dehydrated-namecheap
  namespace: ingress-controller
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create