apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: dehydrated-namecheap
  name: dehydrated-namecheap
  namespace: ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dehydrated-namecheap
subjects:
- kind: ServiceAccount
  name: dehydrated-namecheap
  namespace: ingress-controller
