apiVersion: v1
kind: Secret
metadata:
  labels:
    app: dehydrated-namecheap
  name: dehydrated-namecheap-dhnv
  namespace: ingress-controller
type: Opaque
data:
  apiusr: "base64-encoded"
  apikey: "base64-encoded"
